[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "image2excel"
version = "0.1.0"
description = "converts images to excel tables"
authors = [{ email = "michel.kluger@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "numpy>=2.0.0",
    "openpyxl>=3.1.0",
    "pandas>=2.0.0",
    "pillow>=10.0.0",
    "matplotlib>=3.9.0",
    "colormap>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/michelkluger/image2excel"
"Bug Tracker" = "https://github.com/michelkluger/image2excel/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
python_version = "3.12"
files = ["src"]
strict = true
ignore_missing_imports = true