[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "image2excel"
version = "0.1.0"
description = "converts images to excel tables"
authors = [{ email = "michel.kluger@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3"
dependencies = [
    "pandas",
    "Pillow",
    "colormap",
    "openpyxl",
    "XlsxWriter",
    "Jinja2",
    "easydev",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/michelkluger/image2excel"
"Bug Tracker" = "https://github.com/michelkluger/image2excel/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
image2excel = ["py.typed"]

[tool.setuptools]
py-modules = ["image2excel"]

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }
