[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "image2excel"
version = "0.1.0"
description = "converts images to excel tables"
authors = [{ email = "michel.kluger@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3"


dependencies = [
    "asttokens==2.4.1",
    "colorama==0.4.6",
    "colormap==1.2.0",
    "comm==0.2.2",
    "contourpy==1.3.0",
    "cycler==0.12.1",
    "debugpy==1.8.7",
    "decorator==5.1.1",
    "et_xmlfile==2.0.0",
    "executing==2.1.0",
    "fonttools==4.54.1",
    "ipykernel==6.29.5",
    "ipython==8.29.0",
    "jedi==0.19.1",
    "jupyter_client==8.6.3",
    "jupyter_core==5.7.2",
    "kiwisolver==1.4.7",
    "matplotlib==3.9.2",
    "matplotlib-inline==0.1.7",
    "mypy==1.13.0",
    "mypy-extensions==1.0.0",
    "nest-asyncio==1.6.0",
    "numpy==2.1.3",
    "openpyxl==3.1.5",
    "packaging==24.1",
    "pandas==2.2.3",
    "pandas-stubs==2.2.3.241009",
    "parso==0.8.4",
    "pillow==11.0.0",
    "platformdirs==4.3.6",
    "prompt_toolkit==3.0.48",
    "psutil==6.1.0",
    "pure_eval==0.2.3",
    "Pygments==2.18.0",
    "pyparsing==3.2.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "pywin32==308",
    "pyzmq==26.2.0",
    "six==1.16.0",
    "stack-data==0.6.3",
    "tornado==6.4.1",
    "traitlets==5.14.",
    "types-openpyxl==3.1.5.20241025",
    "types-pytz==2024.2.0.20241003",
    "typing_extensions==4.12.2",
    "tzdata==2024.2",
    "wcwidth==0.2.13",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]



[project.urls]
"Homepage" = "https://github.com/michelkluger/image2excel"
"Bug Tracker" = "https://github.com/michelkluger/image2excel/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
image2excel = ["py.typed"]

[tool.setuptools]
py-modules = ["image2excel"]

[tool.setuptools.dynamic]
readme = { file = ["README.md"], content-type = "text/markdown" }

[tool.my_tool]
config_file = "config.yaml"


[tool.mypy]
python_version = "3.12" 
files = ["src"]  # List of files or directories to check
strict = true # Enable strict mode
ignore_missing_imports = false 

# Enable essential type checking options
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

# Add numpy plugin for better numpy typing
# plugins = ["numpy.typing.mypy_plugin"]

no_implicit_reexport = true # Check variable redefinitions

show_error_codes = true # Show detailed error messages for more context
show_column_numbers = true

warn_unreachable = true # Warn about unreachable code
warn_unused_ignores = true # Warn about unused # type: ignore comments

[[tool.mypy.overrides]]
module = "colormap.*"
ignore_missing_imports = true
