name: Python Mypy Check

on:
  push:
    branches: [type]
  pull_request:
    branches: [type]

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.5.0"

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip sync pyproject.toml

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy . --strict --show-error-codes --pretty