name: Python Mypy Check

on:
  push:
    branches: [type]
  pull_request:
    branches: [type]

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/pyproject.toml

    - name: Install Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        #uv pip install -r requirements.txt  # Uncomment if you have requirements.txt
        uv pip install mypy

    - name: Run mypy
      run: mypy . --strict --show-error-codes --pretty