name: Python Mypy Check

on:
  push:
    branches: [type]  # Run mypy on each push to main
  pull_request:
    branches: [type]  # Run mypy on each PR to main

jobs:
  mypy-check:
    runs-on: windows-latest  # Specify your OS (windows-latest, ubuntu-latest, etc.)

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/Scripts/activate  # Use `source venv/bin/activate` on Ubuntu
        #pip install -r requirements.txt  # Ensure mypy is in your requirements
        pip install mypy

    - name: Run mypy
      run: |
        . venv/Scripts/activate
        mypy . --strict --show-error-codes --pretty