name: Pyre Type Checking

on: [push, pull_request]

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Run Pyre
        uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d
        
      # If you need to upload artifacts, use v3
      - name: Upload Pyre results
        uses: actions/upload-artifact@v3
        with:
          name: pyre-results
          path: .pyre
